language: node_js

sudo: required

cache:
  directories:
    - node_modules

services:
  - docker

before_install:
  - docker-compose up --no-start build
  - docker-compose run build bash -c "yarn install --ignore-engines"

install: true # to avoid the default install step

script:
  - docker-compose run --rm build bin/no-only
  - docker-compose run build bash -c "yarn test"

before_deploy:
  - docker-compose run build bash -c "yarn deploy:prepare"
  - docker-compose run build bash -c "yarn docs:build"

deploy:
  - provider: npm
    edge: true
    email: $NPM_EMAIL
    api_token: $NPM_API_TOKEN
    src: npm-supporticon
    run: docker-compose run --rm build bin/announce
    on:
      tags: true
  - provider: pages
    edge: true
    token: $GITHUB_TOKEN
    keep_history: true
    local_dir: styleguide
    on:
      tags: true
