version: 2.1

parameters:
  PRISMIC_DOCUMENT_REF:
    type: string
    default: ""

workflows:
  version: 2
  staging:
    jobs:
      - staging:
        filters:
          branches:
            ignore: master

  publish:
    jobs:
      - publish:
          filters:
            branches:
              only: master

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies 📦
          command: yarn install --ignore-engines
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  lint:
    steps:
      - run:
          name: Lint 🛠
          command: yarn test

  styleguide:
    steps:
      - run:
          name: Build Styleguide
          command: yarn docs:build
      - run:
          name: Configure Git
          command: |
              git config user.email $GITHUB_EMAIL
              git config user.name $GITHUB_NAME
      - add_ssh_keys:
          fingerprints:
              - $GITHUB_SSH
      - run:
          name: Deploy Styleguide
          command: yarn docs:deploy

  publish:
    steps:
      - run:
          name: Prepare for NPM Publish
          command: yarn deploy:prepare
      - run:
          name: Publish to NPM
          working_directory: /npm-supporticon
          command: |
              npm set //registry.npmjs.org/:_authToken=$NPM_TOKEN
              npm publish
      - run:
          name: Announce Release
          command: yarn announce

jobs:
  staging:
    docker:
      - image: circleci/node:6
    steps:
      - install
      - lint

  publish:
    docker:
      - image: circleci/node:6
    steps:
      - install
      - lint
      - publish
