version: 2.1

orbs:
  npm-publisher: uraway/npm-publisher@0.2.0

workflows:
  version: 2
  test:
    jobs:
      - test:
        filters:
          branches:
            ignore:
              - master
              - gh-pages

  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master

commands:
  install:
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies 📦
          command: yarn install --ignore-engines
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
  lint:
    steps:
      - run:
          name: Lint 🛠
          command: yarn test

  docs:
    steps:
      - add_ssh_keys:
          fingerprints:
            - "db:88:4b:34:dd:32:8c:2c:7e:95:9d:f8:db:5e:d7:28"
      - run:
          name: Setup git user
          command: |
            git config user.email "ci-build@blackbaud.com"
            git config user.name "ci-build"
      - run:
          name: Publish Docs 📄
          command: yarn docs:build && yarn docs:deploy

  publish:
    steps:
      - npm-publisher/publish-from-package-version:
          pre-publish-steps:
            - run:
                name: Prepare for NPM Publish
                command: yarn deploy:prepare
          post-publish-steps:
            - run:
                name: Announce Release
                command: yarn announce
          publish-token-variable: NPM_TOKEN
          package-path: npm-supporticon

jobs:
  test:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - install
      - lint

  deploy:
    docker:
      - image: cimg/node:18.17.0
    steps:
      - install
      - lint
      - publish
