---
steps:
  - type: "waiter"

  - name: ":mag: :fist:"
    command: "docker-compose run --rm build bin/no-only"

  - wait

  - name: ":nodejs: Test It"
    command: "docker-compose run --rm build bin/test"

  - wait

  - name: ":shipit: Deploy Styleguide"
    command: "docker-compose run --rm build bin/staging"
    branches: master

  - wait

  - name: ":shipit: Deploy NPM Package"
    command: "docker-compose run --rm build bin/deploy"
    branches: master

  - wait

  - name: ":loudspeaker: Announce It"
    command: "./bin/announce"
    branches: master
